---
title: "Projet Oraccle"
subtitle: "Visualisation des données"
date: "Dernière modification le `r format(Sys.time(), '%d %B %Y')`"
output:
    rmarkdown::html_document:
      #number_sections: true
      theme: paper
      toc: true
      toc_depth: 4
      collapsed: true
      smooth_scroll: true
      css: styles.css
      code_folding: hide
      includes:
        in_header: header.html
        after_body: footer.html
---

```{r setup, include=FALSE}
# Paramètres généraux
knitr::opts_chunk$set(
	eval = TRUE,
	echo = FALSE,
	fig.align = "center",
	fig.show = "hold",
	message = FALSE,
	warning = FALSE,
	collapse = TRUE,
	out.width = "100%",
	results = "asis"
)
```

```{r logo}
# Logo Datactivist haut de page
htmltools::img(src = "https://nextcloud.datactivist.coop/s/o53wzfMNnFosQni/preview", 
               alt = 'logo', 
               style = 'position:absolute; top:0; left:0.5; padding-top:10px;') #padding=taille des espaces autour
```

# Dataviz

```{r import data et librairies}
library(tidyverse)
library(plotly)
library(flexdashboard)
library(icons)

# Import données
cohortes_age_premiereins <- read_delim("../data/France/cohorte_age_premiereins.csv", ";")
cohorte_anbac <- read_delim("../data/France/cohorte_anbac.csv", ",")
cohorte_bac <- read_delim("../data/France/cohorte_bac.csv", ",")
cohorte_derniereins <- read_delim("../data/France/cohorte_derniereins.csv", ",")
cohorte_premiereins <- read_delim("../data/France/cohorte_premiereins.csv", ",")
cohorte_sexe <- read_delim("../data/France/cohorte_sexe.csv", ",")
cohorte_spe <- read_delim("../data/France/cohorte_spe.csv", ",")
cohortes <- read_delim("../data/France/cohortes.csv", ",")
formations <- read_delim("../data/France/formations.csv", ",")
```


# Statistiques exploratoires

```{r}
# Exploration 
test <- table(cohorte_spe$bac_spe1) |> as.data.frame() |> arrange(desc(Freq))

```

```{r}
# Nombre d'établissements
extraire_troisieme <- function(liste) {
  troisiemes_elements <- sapply(liste, function(element) {
    parties <- unlist(strsplit(element, split = "-"))
    return(parties[3])
  })
  return(troisiemes_elements)
}

test <- cohortes[1:1000,]
test2 <- test |> 
    mutate(etablissements = str_extract_all(trace, "(?:[^+-]+-){2}([^+-]+)"))
test2$troisiemes_elements <- sapply(test2$etablissements, extraire_troisieme)


# Table
df <- data.frame(
    x = c(2, 8.5, 15, 21.5),
    y = rep(6.5, 4),
    h = rep(4.25, 4),
    w = rep(6.25, 4),
    value = c(nrow(cohortes), sum(cohortes$effectif), 0, 0),
    info = c("cohortes",
             "étudiants",
             "établissements",
             "formations"),
    color = factor(1:4)
)

# Graphique
ggplot(df, aes(x, y, height = h, width = w, label = info)) +
    ## Create the tiles using the `color` column
    geom_tile(aes(fill = color)) +
    ## Add the numeric values as text in `value` column
    geom_text(color = "white", fontface = "bold", size = 8,
              aes(label = ifelse(value > 999, format(as.integer(value, 0), nsmall = 1, big.mark = "."), value), 
                  x = x, y = y + 0.7), 
              hjust = 0.5) +
    ## Add the labels for each box stored in the `info` column
    geom_text(color = "white", fontface = "bold", size = 4,
              aes(label = info, x = x - 2.9, y = y - 1), hjust = 0) +
    coord_fixed() +
    #scale_fill_manual(type = "qual", palette = "Dark2") +
    scale_fill_manual(values = c("#fd710f", "#fe44d5", "#ede5e0", "#fb7564")) +
    ## Use `geom_text()` to add the icons by specifying the unicode symbol.
    theme_void() +
    guides(fill = FALSE)

```


# Visulisations exploratoires

```{r année bac}
# Custom_theme pour ggplot
custom_theme <- function (){
    font <- "Helvetica"
    ggplot2::theme(plot.title = ggplot2::element_text(family = font,size = 19, face = "bold", color = "#222222"), 
        plot.subtitle = ggplot2::element_text(family = font,size = 18, face = "italic", margin = ggplot2::margin(0, 0, 9, 0)), 
        plot.caption = ggplot2::element_text(family = font,size = 15, face = "italic", color = "#666666", margin = ggplot2::margin(9, 0, 9, 0)), 
        plot.tag = ggplot2::element_text(size = 15),
        #plot.tag.position = "topright",
        plot.caption.position = "plot",
        legend.title = ggplot2::element_text(family = font, size = 18, color = "#222222"), 
        legend.position = "top", 
        legend.text.align = 0, 
        legend.background = ggplot2::element_blank(),
        legend.key = ggplot2::element_blank(),
        legend.text = ggplot2::element_text(family = font, size = 18,color = "#222222"), 
        axis.text = ggplot2::element_text(family = font, size = 15,color = "#222222"), 
        axis.text.x = ggplot2::element_text(margin = ggplot2::margin(5,b = 10), size = 12), 
        axis.title = ggplot2::element_text(family = font, size = 18,color = "#222222"),
        axis.ticks = ggplot2::element_blank(),
        axis.line = ggplot2::element_blank(), 
        panel.grid.minor = ggplot2::element_blank(),
        panel.grid.major.y = ggplot2::element_line(color = "#cbcbcb"),
        panel.grid.major.x = ggplot2::element_blank(), 
        panel.background = ggplot2::element_blank(),
        strip.background = ggplot2::element_rect(fill = "white"),
        strip.text = ggplot2::element_text(size = 22, hjust = 0, face = "bold"))
}

# Année du bac
    # Préparation des données
table <- cohorte_anbac |> 
    summarise(nb_etudiants = sum(effectif, na.rm = TRUE), .by = anbac) |> 
    filter(nb_etudiants > 0)
    # Dataviz
graph <- ggplot(table) +
  aes(x = anbac, y = nb_etudiants, text = paste("Année du bac :", anbac,
                                                "\nNombre d'étudiants :", nb_etudiants)) +
  geom_col(fill = "#fd710f", col = "white", alpha = .7) +
  scale_y_continuous(labels = scales::comma) +
  labs(x = "Année d'obtention", y = "Nombre d'étudiants",
       title = "Année d'obtention du baccalauréat des étudiants") +
  theme_minimal() +
  custom_theme()
ggplotly(graph, tooltip = c("text"))
```

<br>

```{r sexe cohortes}
# Sexe des étudiants
    # Préparation des données
cohorte_sexe <- cohorte_sexe |> 
    mutate(cohorteid = as.character(cohorteid),
           sexe = case_match(sexe, 1 ~ "homme", 2 ~ "femme"),
           nb_etudiants_cohorte = sum(effectif), 
           percent = round(effectif / nb_etudiants_cohorte, 5),
           .by = cohorteid)
table_femmes <- cohorte_sexe |> 
    filter(sexe == "femme")
    # Dataviz
ggplot(data = table_femmes) + 
  geom_histogram(mapping = aes(x = percent, y=..density..), fill = "#fd710f", color = "white", alpha = .7) +
  stat_function(fun = dnorm, args = list(mean = mean(table_femmes$percent), sd = sd(table_femmes$percent)), 
                size = 1, alpha = .8, aes(col = "Distribution normale")) +
  scale_colour_manual("", values = c("#cb1d27")) +
  labs(title = "Distribution de la part des femmes dans les cohortes", x = "Pourcentage de femmes", y = "Densité") +
  theme_classic() +
  scale_x_continuous(labels = scales::percent, limits = c(0,1)) +
  geom_vline(xintercept = .5, linetype = 2, col = "#666666", linewidth = .7) +
  custom_theme() +
  theme(plot.title = ggplot2::element_text(size = 18))
```





```{r draft, eval=FALSE, include=FALSE}
table |> 
    filter(sexe == "femme") |> 
    ggplot(aes(x = 1, y = as.numeric(percent))) + 
      geom_violin(trim = F, fill = "#fd710f", position="identity", alpha = .7, scale = "width") + #scale pour avoir même hauteur
      coord_flip() +
      labs(y = "Centro de gravedad", x = "", 
           title = "tt", 
           subtitle = "Datos de 11 pacientes") +
      theme_classic() +
     # scale_y_continuous(labels = scales::percent, limits = c(0,1)) +
      geom_vline(xintercept = .5, linetype = 2, col = "#666666", linewidth = .7) +
      custom_theme() +
      guides(fill = guide_legend(title = "", reverse = F))
```

